### ISSUE TITLE
上传到mihomotproxy报错

### ISSUE THREAD

**Issue by 77160860** [refined-fish/clash_rule_fish#3]
time="2024-12-14T15:44:16.742652971+08:00" level=error msg="yaml: line 120: could not find expected ':'"
configuration file /etc/mihomo/run/config.yaml test failed

**Comment by refined-fish** [comment]
报错说你的yaml120行有问题，你不要光贴日志，贴一下对应的yaml我看看呢

**Comment by 007learner** [comment]
yaml: line 120: could not find expected ':'"
<img width="720" alt="Screenshot 2025-01-05 at 7 33 21 PM" src="https://github.com/user-attachments/assets/972ba939-0d35-41bc-a3cb-b0478fae4da7" />

**Comment by 007learner** [comment]
同样问题，比较奇怪
level=error msg="yaml: line 118: could not find expected ':'"
<img width="1058" alt="Screenshot 2025-01-05 at 7 35 53 PM" src="https://github.com/user-attachments/assets/ec9e366b-d740-4f34-adc1-341f408d8160" />

**Comment by refined-fish** [comment]
> 同样问题，比较奇怪 level=error msg="yaml: line 118: could not find expected ':'" <img alt="Screenshot 2025-01-05 at 7 35 53 PM" width="1058" src="https://private-user-images.githubusercontent.com/23491529/400194001-ec9e366b-d740-4f34-adc1-341f408d8160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwODU3MTYsIm5iZiI6MTczNjA4NTQxNiwicGF0aCI6Ii8yMzQ5MTUyOS80MDAxOTQwMDEtZWM5ZTM2NmItZDc0MC00ZjM0LWFkYzEtMzQxZjQwOGQ4MTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDEzNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5M2IxZGU4NjliNjExZjBhNDc1NWE1ZjQ1ODJjYzllNjI3NzM0ZmRkOGE0Nzk3MTY5OTRiNjIxNWMzNjYyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ms8bVY4camHyhuepUj9W15_vAvOpCHt1A3NJcxCPaTE">

你可以去掉敏感信息之后发送完整的配置文件给我试试么，我这里没有遇到这个问题，mihomo的日志报错不一定是在准确的位置，我以前遇到过类似的情况

**Comment by 007learner** [comment]
如果说报错不准的话，难道是proxy这里有问题。
完整配置请查看，指正，谢谢。

```
#mixed-port: 7890  #⭕混合端口，系统代理端口
#socks-port: 1080  #⭕SOCKS5 代理端口
#port: 8080  #⭕HTTP 代理端口
redir-port: 7891  #⭕redir 透明代理端口，非linux系会报错
tproxy-port: 7892  #⭕tproxy 透明代理端口，非linux系会报错

###########################################################################################################################
allow-lan: true #⭕允许局域网
bind-address: "*" #⭕监听地址，*为所有
lan-allowed-ips: # 允许连接的客户端IP，默认允许全部
  - 0.0.0.0/0
  - ::/0
lan-disallowed-ips: # 禁止连接的IP，优先级高于白名单
  - ~
authentication: # http(s)/socks/mixed 代理的用户验证，格式："user1:pass1"，不写则禁止全部用户
  - ~
skip-auth-prefixes: # 白名单，允许跳过用户验证的IP
  - ~
mode: rule # 运行模式：rule（规则） / global（全局代理）/ direct（全局直连）
log-level: warning #⭕日志级别
ipv6: true #⭕是否接受ipv6流量
keep-alive-idle: 30 # 触发心跳包的无活动阈值
keep-alive-interval: 30 # 发送心跳包的间隔，最多9次
disable-keep-alive: false # 禁用 keep alive，允许链接一直存在
find-process-mode: off # 进程匹配：strict由mihomo决定是否开启（off:关闭，alwas:开启，tun模式下失效）
external-controller: 0.0.0.0:9090 #⭕API面板监听地址
secret: "hd54RIm0LiUpyu" #⭕API面板访问密钥
external-ui: ./ui #⭕API面板静态资源路径
external-ui-name: zashboard #⭕API面板名，配合路径拼接成路径，例如/ui/metacubexd
external-ui-url: "https://gh-proxy.com/https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip" #⭕API面板下载地址
profile: # 缓存设置
  store-selected: true # 缓存 API面板 对策略组的选择
  store-fake-ip: true # 缓存 fakeip 映射表
unified-delay: false # 统一延迟计算，没啥卵用
tcp-concurrent: true # TCP并发
#interface-name: en0  #⭕clash流量出站接口，即接口绑定
#routing-mark: 6666  # Linux下的路由标记，为流量提供标记
global-client-fingerprint: random # 全局客户端指纹，优先低于其他处的声明
geodata-mode: true # GEOIP数据模式，false:mmdb，true:dat，mmdb更新但有设备不支持
geodata-loader: standard # GEO文件加载模式，默认memconservative（小内存设备模式）
geo-auto-update: true # GEO文件自动更新
geo-update-interval: 24 # 更新间隔，小时
geox-url: # GEO数据库下载地址，内核会按需下载
  geoip: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb"
  asn: "https://gh-proxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
global-ua: clash.meta # 全局UA，默认为clash.meta
etag-support: true # 资源下载的 ETag 支持

###########################################################################################################################
public-dns: &public-dns
  - dhcp://wan # 指定网卡获取的DNS，硬路由的wan口网卡名为wan
  - dhcp://eth2 # 指定网卡获取的DNS，软路由的wan口网卡名为最后一张网卡，双口就是eth1
  - 223.5.5.5 # 阿里主DNS
  - 223.6.6.6 # 阿里副DNS

secure-dns: &secure-dns
  - https://8.8.8.8/dns-query # 谷歌主DNS
  - https://8.8.4.4/dns-query # 谷歌副DNS
  - https://208.67.222.222/dns-query # OpenDNS主DNS
  - https://208.67.220.220/dns-query # OpenDNS次DNS
  - https://1.1.1.1/dns-query#h3=true # Cloudflare主DNS，支持H3
  - https://1.0.0.1/dns-query#h3=true # Cloudflare次DNS，支持H3
  - https://dns.nextdns.io#h3=true # NextDNS，支持H3

dns:
  enable: true #⭕启用dns
  prefer-h3: true # 优先使用HTTP/3，DoH能加速
  listen: 0.0.0.0:1053 #⭕DNS监听端口，仅支持udp
  ipv6: true # 是否解析ipv6地址，否则返回空结果
  enhanced-mode: redir-host #⭕DNS处理模式：redir-host/fake-ip，fake-ip更快但引入问题（缓存fakeip后无法故障切换）
  fake-ip-range: 198.18.0.1/16 # fakeip 下的 IP 段设置，tun接口的默认 IPV4 地址 也使用此值作为参考
  fake-ip-filter: # fakeip过滤
    - geosite:category-ads-all,category-games,cn,private
  fake-ip-filter-mode: blacklist # 黑/白名单模式，白名单下 filter 会返回 fake-ip
  use-hosts: true # 查询配置文件 hosts
  use-system-hosts: true # 查询系统 hosts
  respect-rules: false # DNS请求遵循路由规则，redir-host模式推荐，需先配置好 proxy-server-nameserver，否则出现鸡蛋问题

  default-nameserver:
    - 223.5.5.5 # 解析DNS服务器的域名
  nameserver-policy: # 优先级高于nameserver
    "geosite:category-ads-all": rcode://success # 匹配广告域名
    "geosite:cn,apple,private": *public-dns # 匹配中国，苹果域名，私有地址
    "geosite:geolocation-!cn": *secure-dns # 匹配非中国域名
  proxy-server-nameserver: *public-dns # 解析节点域名的DNS，不指定则遵循namepolicy
  nameserver: *public-dns # 默认DNS组，域名未命中 nameserver-policy 时使用
  direct-nameserver: *public-dns # direct策略组的 DNS 服务器，不填则遵循nameserver-policy

###########################################################################################################################
hosts:
  "mihomo.mihomo": 127.0.0.1

###########################################################################################################################
sniffer: # 嗅探，获取SNI中的域名
  enable: true # 启用sniffer
  force-dns-mapping: true # 对redir-host类型识别的流量进行强制嗅探
  parse-pure-ip: true # 对所有未获取到域名的流量进行强制嗅探
  override-destination: true # 是否使用嗅探结果作为实际访问，默认为 true
  sniff: # 需要嗅探的协议类型，仅支持 HTTP/TLS/QUIC
    TLS: # TLS协议，不配置默认嗅探443端口
    HTTP: # HTTP协议
      ports: # 端口白名单，只针对下列端口嗅探，不配置则全部嗅探
        - 80
  force-domain: # 强制嗅探的域名
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain: # 需要跳过嗅探的域名。主要解决部分站点sni字段非域名，导致嗅探结果异常的问题，如米家设备
    - "+.apple.com"
    - Mijia Cloud
    - dlg.io.mi.com
    - "+.oray.com"
    - "+.sunlogin.net"
    - geosite:cn

###########################################################################################################################
tun:
  enable: false #⭕启用Tun接口
  stack: mixed # TUN 堆栈模式,建议 mixed（TCP：system，UDP：Gvisor）
  device: utun0 # TUN 网卡名，MacOS 只能 utun 开头
  auto-route: true # 自动设置全局路由，自动将全局流量路由进 tun
  auto-redirect: true # 仅Linux有效，自动配置 iptables/nftables 以重定向 TCP 连接，需要auto-route: true
  auto-detect-interface: true # 自动选择流量的出接口（wan）
  dns-hijack: # dns 劫持，将匹配到的连接导入内部 dns 模块，不书写协议则默认 udp://
    - any:53
    - tcp://any:53
  strict-route: true # 严格路由，添加防火墙规则禁止Windows使用多DNS，有效防止DNS泄露
  mtu: 9000 # MTU
  gso: true # 通用分段卸载
  gso-max-size: 65536 # 数据块最大长度
  endpoint-independent-nat: false # 独立于端点的 NAT，性能可能下降，不建议不需要时开启
  exclude-package: # 安卓排除的包名
    - com.tencent.mobileqq # QQ
    - com.tencent.mm # 微信
    - com.tencent.androidqqmail # QQ邮箱
    - com.xingin.xhs # 小红书
    - idm.internet.download.manager # 1DM下载器
    - com.sausage.download # 浩克下载
    - com.eg.android.AlipayGphone # 支付宝
    - com.sgcc.wsgw.cn # 网上国网
    - com.taobao.taobao # 淘宝
    - com.jingdong.app.mall # 京东
    - com.MobileTicket # 铁路12306
    - com.chinamworld.main # 中国建设银行
    - com.jd.jrapp # 京东金融

###########################################################################################################################

proxies:
- name: "ss"
  type: ss
  server: 1.2.3.4
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "abcdenfg"
  ip-version: ipv4
  udp: true


proxy-providers-general: &proxy-providers-general
  type: http # 类型，可选http/file
  interval: 86400
  proxy: DIRECT
  size-limit: 0
  override:
    tfo: false # 启用TCP Fast Open，一般都不支持
    mptcp: false # 启用TCP Multi Path，一般都不支持
    udp: true
    udp-over-tcp: false # 启用 UDP over TCP
    skip-cert-verify: false # 跳过证书验证

proxy-providers:
  #❗provider占位1
  #❗provider占位2
  #❗provider占位3
  #❗provider占位4

###########################################################################################################################
use-all-proxy-providers: &use-all-proxy-providers
  use:
    #❗use-provider占位1
    #❗use-provider占位2
    #❗use-provider占位3
    #❗use-provider占位4

health-check-general: &health-check-general
  <<: *use-all-proxy-providers
  url: http://www.gstatic.com/generate_204
  interval: 30
  tolerance: 200
  lazy: true
  timeout: 5000

proxy-groups:
  - name: ♻️延迟最低
    type: url-test
    <<: *health-check-general

  - name: ⚠️故障切换
    type: fallback
    <<: *health-check-general

  - name: 🐟漏网之鱼
    type: select
    proxies:
      - DIRECT
      - ♻️延迟最低
      - 🇭🇰香港节点
      - 🇨🇳台湾节点
      - 🇸🇬狮城节点
      - 🇯🇵日本节点
      - 🇺🇲美国节点
      - 🖐️手动切换

  - name: 🖐️手动切换
    type: select
    <<: *use-all-proxy-providers

  - name: Ⓜ️微软Copilot
    type: select
    proxies:
      - ⚠️故障切换
      - ♻️延迟最低
      - 🇭🇰香港节点
      - 🇨🇳台湾节点
      - 🇸🇬狮城节点
      - 🇯🇵日本节点
      - 🇺🇲美国节点
      - 🖐️手动切换
      - DIRECT
    icon: https://gh-proxy.com/https://github.com/refined-fish/clash_rule_fish/blob/main/Icons/Microsoft_365_Copilot.png

  - name: ⏣OpenAi
    type: select
    proxies:
      - 🇸🇬狮城节点
      - ♻️延迟最低
      - 🇭🇰香港节点
      - 🇨🇳台湾节点
      - 🇯🇵日本节点
      - 🇺🇲美国节点
      - 🖐️手动切换
    icon: https://gh-proxy.com/https://github.com/refined-fish/clash_rule_fish/blob/main/Icons/Chat_GPT.png

  - name: ✈️Telegram
    type: select
    proxies:
      - ♻️延迟最低
      - 🇭🇰香港节点
      - 🇨🇳台湾节点
      - 🇸🇬狮城节点
      - 🇯🇵日本节点
      - 🇺🇲美国节点
      - 🖐️手动切换
    icon: https://gh-proxy.com/https://github.com/refined-fish/clash_rule_fish/blob/main/Icons/Telegram.png

  ###########################
  - name: 🇭🇰香港节点
    type: url-test
    <<: *health-check-general
    filter: "港|HK|hk|Hong Kong|HongKong|hongkong"

  - name: 🇯🇵日本节点
    type: url-test
    <<: *health-check-general
    filter: "日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan"

  - name: 🇺🇲美国节点
    type: url-test
    <<: *health-check-general
    filter: "美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"

  - name: 🇨🇳台湾节点
    type: url-test
    <<: *health-check-general
    filter: "台|新北|彰化|TW|Taiwan"

  - name: 🇸🇬狮城节点
    type: url-test
    <<: *health-check-general
    filter: "新加坡|坡|狮城|SG|Singapore"

###########################################################################################################################
rule-providers-general: &rule-providers-general
  type: http
  behavior: classical
  interval: 86400

rule-providers:
  ♻️延迟最低-FISH:
    <<: *rule-providers-general
    url: https://gh-proxy.com/https://raw.githubusercontent.com/refined-fish/clash_rule_fish/refs/heads/main/Ruleset/♻️延迟最低-FISH.yaml
    path: ./providers/rule-provider_♻️延迟最低-FISH.yaml

  🌐Direct-FISH:
    <<: *rule-providers-general
    url: https://gh-proxy.com/https://raw.githubusercontent.com/refined-fish/clash_rule_fish/refs/heads/main/Ruleset/🌐Direct-FISH.yaml
    path: ./providers/rule-provider_🌐Direct-FISH.yaml

  UnBan:
    <<: *rule-providers-general
    url: https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/UnBan.yaml
    path: ./providers/rule-provider_UnBan.yaml

  Ⓜ️微软Copilot-FISH:
    <<: *rule-providers-general
    url: https://gh-proxy.com/https://raw.githubusercontent.com/refined-fish/clash_rule_fish/refs/heads/main/Ruleset/%E2%93%82%EF%B8%8F%E5%BE%AE%E8%BD%AFCopilot-FISH.yaml
    path: ./providers/rule-provider_Ⓜ️微软Copilot-FISH.yaml

  Ⓜ️微软服务: # ACL4SSR@微软服务（GEO@Microsoft疑似影响onedrive同步）
    <<: *rule-providers-general
    url: https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Microsoft.yaml
    path: ./providers/rule-provider_Ⓜ️微软服务.yaml

###########################################################################################################################
rules:
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT # CN运营商UDP有QoS，禁用QUIC
  # FISH自定义规则块
  - DOMAIN,portal.office.com,🇭🇰香港节点 # FISH-避免IP变动过大
  - DOMAIN-SUFFIX,asmrbbs.com,🇭🇰香港节点 # FISH-避免IP变动过大
  - RULE-SET,♻️延迟最低-FISH,♻️延迟最低 # FISH自定义代理
  - RULE-SET,🌐Direct-FISH,DIRECT # FISH自定义直连
  # 广告拦截与局域网/下载绕过块
  - GEOIP,private,DIRECT,no-resolve # 私有地址直连
  - GEOSITE,private,DIRECT # 私有地址直连
  - RULE-SET,UnBan,DIRECT # 解除ads-all中的部分域名
  - GEOSITE,category-ads-all,REJECT # 广告拦截
  # 代理规则块，按照使用频率/规则集大小排序
  - GEOSITE,google@cn,DIRECT # Google中国直连
  - RULE-SET,Ⓜ️微软Copilot-FISH,Ⓜ️微软Copilot # 微软copilot代理-FISH自定义
  - GEOSITE,github,♻️延迟最低 # Github代理
  - RULE-SET,Ⓜ️微软服务,DIRECT # 微软服务直连，GEO的微软服务涵盖太过广泛
  - GEOSITE,category-games@cn,DIRECT # 各种游戏直连
  - GEOSITE,steam,♻️延迟最低 # Steam商店、社区代理
  - GEOSITE,openai,⏣OpenAi # OpenAi代理
  - GEOSITE,telegram,✈️Telegram # Telegram代理
  - GEOIP,telegram,✈️Telegram,no-resolve # Telegram代理
  - GEOSITE,docker,♻️延迟最低 # Docker代理
  - GEOSITE,bahamut,🇨🇳台湾节点 # 巴哈姆特台湾代理
  - GEOSITE,category-porn,♻️延迟最低 # X代理
  # 兜底规则块，一般规则应在其上
  - GEOSITE,gfw,♻️延迟最低 # GFW兜底
  - GEOSITE,cn,DIRECT # 中国直连
  - GEOIP,cn,DIRECT,no-resolve # 中国直连
  - MATCH,🐟漏网之鱼 # 漏网之鱼

```
